SELECT
##T是临时产生的抽出结果
    T.MEIKNJ
  , T.MEIKNA
  , T.CARDNO
  , T.CARDSTCD
  , T.CARDSYUMEI
  , T.JTTELNO
  , T.MCMUKEYMD
  , T.TENRYAK
  , T.BIRTH
  , T.SEIBT
  , T.FMLKBN
  , T.YUKODATE
  , T.STACIANO
  , T.KAISTCD
  , T.DAIKANNO
  , T.KTITELNO
  , T.JTYUBNNO
  , T.JTAREKNJ1
  , T.JTAREKNJ2
  , T.NKIENTYMD
  , T.MAIL
  , T.KTIMAIL
  , T.TKIYMD
  , T.TKIST
  , T.KAIKANNO

FROM
  (SELECT
        PT02.MEIKNJ
      , PT02.MEIKNA
      , PT03.CARDNO
      , PT03.CARDSTCD
      , PT10.CARDSYUMEI
      , PT01.JTTELNO
      , PT02.MCMUKEYMD
      , PT15.TENRYAK
      , PT02.BIRTH
      , PT02.SEIBT
      , PT02.FMLKBN
      , PT02.YUKODATE
      , PT03.STACIANO
      , PT02.KAISTCD
      , PT01.DAIKANNO
      , PT01.KTITELNO
      , PT01.JTYUBNNO
      , PT01.JTAREKNJ1
      , PT01.JTAREKNJ2
      , PT02.NKIENTYMD
      , PT02.MAIL
      , PT02.KTIMAIL
      , PT02.TKIYMD
      , PT02.TKIST
      , PT02.KAIKANNO
    FROM
        ipossch.PT01
  INNER JOIN ipossch.PT02
      ON PT02.KANKAISHACD = PT01.KANKAISHACD
     AND PT02.DAIKANNO = PT01.DAIKANNO
   INNER JOIN ipossch.PT03
      ON PT03.KANKAISHACD = PT02.KANKAISHACD
     AND PT03.KAIKANNO = PT02.KAIKANNO
   INNER JOIN ipossch.PT10
      ON PT10.KANKAISHACD = PT03.KANKAISHACD
     AND PT10.CARDSYUCD = PT03.CARDSYUCD
   INNER JOIN ipossch.PT15
	     ON PT15.KANKAISHACD = PT02.KANKAISHACD
     AND PT15.KAISHACD = PT02.NKIKAISHACD
     AND PT15.TENCD = PT02.NKITENCD
   WHERE
        PT02.GSNSKAIKANNO = '99'
        AND PT01.KANKAISHACD = '01'
        AND PT03.DELFLG = '0'
        AND PT02.DELFLG = '0'
        AND PT01.DELFLG = '0'
        AND PT10.DELFLG = '0'
        AND PT15.DELFLG = '0'
    UNION
        SELECT
              PT02.MEIKNJ
          , PT02.MEIKNA
          , PT03.CARDNO
          , PT03.CARDSTCD
          , PT10.CARDSYUMEI
          , PT01.JTTELNO
          , PT02.MCMUKEYMD
          , PT15.TENRYAK
          , PT02.BIRTH
          , PT02.SEIBT
          , PT02.FMLKBN
          , PT02.YUKODATE
          , PT03.STACIANO
          , PT02.KAISTCD
          , PT01.DAIKANNO
          , PT01.KTITELNO
          , PT01.JTYUBNNO
          , PT01.JTAREKNJ1
          , PT01.JTAREKNJ2
          , PT02.NKIENTYMD
          , PT02.MAIL
          , PT02.KTIMAIL
          , PT02.TKIYMD
          , PT02.TKIST
          , PT02.KAIKANNO
        FROM
				ipossch.PT01
	      INNER JOIN ipossch.PT02
	 		 ON PT02.KANKAISHACD = PT01.KANKAISHACD
	 		AND PT02.DAIKANNO = PT01.DAIKANNO
	 	  INNER JOIN ipossch.PT03
	 	     ON PT03.KANKAISHACD = PT02.KANKAISHACD
	 	    AND PT03.KAIKANNO = PT02.KAIKANNO
	 	  INNER JOIN ipossch.PT10
	 	     ON PT10.KANKAISHACD = PT03.KANKAISHACD
	 	    AND PT10.CARDSYUCD = PT03.CARDSYUCD
	 	  INNER JOIN ipossch.PT15
	 	     ON PT15.KANKAISHACD = PT02.KANKAISHACD
	 	    AND PT15.KAISHACD = PT02.NKIKAISHACD
	 	    AND PT15.TENCD = PT02.NKITENCD
       WHERE
               PT02.KAIKANNO = '99'
            AND PT01.KANKAISHACD = '01'
            AND PT03.DELFLG = '0'
            AND PT02.DELFLG = '0'
            AND PT01.DELFLG = '0'
            AND PT10.DELFLG = '0'
            AND PT15.DELFLG = '0') T
##T是临时产生的抽出结果
      ORDER BY DAIKANNO ASC, KAIKANNO ASC , CARDNO ASC

